### PR TITLE
Upgrade to Spark 3.3.0

### LINKED ISSUE #191: Support for Spark 3.3
Hi, when I try to use the connector with Spark 3.3 my Spark jobs crash with the following stack trace:

```
Caused by: java.lang.NoSuchMethodError: 'scala.Function0 org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.createConnectionFactory(org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions)'
	at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:56)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:109)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:169)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:95)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:779)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:94)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:176)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:584)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:560)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:81)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:116)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:860)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:390)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:363)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
        ...
```

I know that there's no official support for Spark 3.2 (see also #164), but so far it has worked for me anyways. However, after upgrading to 3.3, the exception above appears.

I am using Databricks and want to upgrade to [Databricks runtime version 11.0](https://docs.databricks.com/release-notes/runtime/11.0.html), which uses Spark 3.3 now. However, this connector is the only dependency that still prevents us from upgrading.

### PR DESCRIPTION
**Pull request by moredatapls**
- Bump Spark to 3.3.0: replaced the usage of the removed `JdbcUtils.getConnectionFactory` with an own implementation
- Add integration tests to
  - create a JDBC connection using the new utils
  - write data to and read data from a SQL server
- Added a docker compose setup to spin up a local instance of SQL server
- Bumped the version of the library to 1.3.0
- Updated the readme accordingly
  - Added the 1.3.0 artifact to the version table
  - Added instructions on how to run the tests

Fixes #191

### CODE REVIEW

**Review by SteffenMangold — COMMENTED** [review]
Build fails 😋

**Review by SteffenMangold — DISMISSED** [review]
Works now

**Comment by moredatapls** [comment]
I want to push one release first before I merge this for Spark 3.2 which has been requested a lot in the Microsoft repo, so I will put this back into draft for now

**Comment by moredatapls** [comment]
closed in favor of #8

**Pull request closed without merging**
